name = "Las Soposas Aventuras de Edgar y Owen"
author = "Ekinox0310"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d6de409810a7ebcc5fce0026e4e132256c8c4ab5cc42a68165d4bd23ba955b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[options]
acceptable-game-versions = ["1.21.1"]
