name = "Las Soposas Aventuras de Edgar y Owen"
author = "Ekinox0310"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca559ce8d937c9c04645010aa20ca5b7f8d2493a8a350fa21d406494efea84cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[options]
acceptable-game-versions = ["1.21.1"]
