name = "Las Soposas Aventuras de Edgar y Owen"
author = "Ekinox0310"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52c119cb7a3ec1d34bcf728242a551214d8f624f39e7f32f06a008ba98f5ec64"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21.1"]
