name = "Las Soposas Aventuras de Edgar y Owen"
author = "Ekinox0310"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54e5ea3d9fc253c08006b04188b43f41f8bb717056cf321d23afa737542ec8ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[options]
acceptable-game-versions = ["1.21.1"]
