name = "Las Soposas Aventuras de Edgar y Owen"
author = "Ekinox0310"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d8b75de7befa9ac95201fc2693df6ddfff2567054cd227e2d8036449c191b10"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[options]
acceptable-game-versions = ["1.21.1"]
